# -*- coding:Utf-8 -*-

import logging
from BeautifulSoup import BeautifulSoup, Comment
from jinja2 import Template

TEMPLATE = u"""\
<html>
<head>
    <title>WarGod - {{ title }}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <style>
    #title
    {
        margin-left: 8%%;
        margin-top: 40px;
        margin-bottom: 40px;
        font-size: 42px;
    }
    #content
    {
        margin-left: 12%%;
        margin-right: 12%%;
    }
    .item
    {
        margin-bottom: 55px;
        padding: 4px;
    }
    .item-title
    {
        padding: 4px;
        padding-left: 15px;
        padding-right: 15px;
        margin-top: 0px;
        margin-bottom: 0px;
        border-bottom: 3px solid;
    }
    .item-description
    {
        padding: 4px;
        margin-left: 35px;
        margin-right: 35px;
        margin-top: 3px;
        margin-bottom: 0px;
    }
    .separator
    {
        text-align: center;
        margin-bottom: 74px;
        border-top: 1px solid #DDDDDD;
        margin-left: 38%%;
        margin-right: 38%%;
    }
    .item-title a
    {
        color: #555555;
        text-decoration: none;
    }
    p
    {
        font-size: 20px;
    }
    .inner-description
    {
        padding: 0px;
        margin: 0px;
    }
    </style>
</head>
<body>
    <h1 id="title">WarGod</h1>
    <div id="content">

    {% for entry in entries %}
        <div class="item">
            <p class="item-title"><a href="{{ entry.link }}">{{ entry.title }}</a> - <a href="{{ entry.site.link }}">{{ entry.site.title }}</a></p>
            <div class="item-description">
                <p class="inner-description">
                {{ entry.description }}
                </p>
            </div>
        </div>

        <p class="separator"> </p>
    {% endfor %}

    </div>
<p style="text-align: center;">Page generated by WarGod</p>
</body>
</html>"""


def generate_html(entries, title="default"):
    logging.debug("starting html generation using jinja2 template")
    result = Template(TEMPLATE).render(entries=map(lambda x: clean_html(x), entries)[::-1], title=title)
    logging.debug("end of html generation")
    return result

def clean_html(entry):
    description = BeautifulSoup(entry["description"])
    logging.debug("cleaning %s" % entry["link"])
    for div in description('div'):
        logging.debug("clean attrs from %s" % div)
        div.attrs = tuple()
    for p in description('p'):
        logging.debug("clean attrs from %s" % p)
        p.attrs = tuple()
    for comment in description.findAll(text=lambda x: isinstance(x, Comment)):
        logging.debug("remove comment: %s" % comment)
        comment.extract()
    for script in description('script'):
        logging.debug("remove script: %s" % script)
        script.extract()
    #from ipdb import set_trace; set_trace()
    logging.debug("end of cleaning %s" % entry["link"])
    entry["description"] = u"%s" % description
    return entry
